apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sajidwebapp
  name: sajidwebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sajidwebapp
  type: LoadBalancer
status:
  loadBalancer: {}
